### ISSUE TITLE
Readme.md  - Incorrect Bootstrap reference 

### ISSUE THREAD

**Issue by mrsoto** [strongloop/loopback-example-angular-starter#15]
The reference to Bootstraps is incorrect 
Suggested fix in #13 commit
https://github.com/mrsoto/loopback-example-angular-starter/commit/1bcddcdb07d246bd3ce427d3226c67db9ff328c9

**Comment by superkhau** [comment]
This example is deprecated. There is a note at the top of the README stating this. See strongloop/loopback-example-angular for a recent version. Please see if you have any issues with the updated example. Thanks for the report though.
